// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentManagement.Entity
{
    public partial class StudentDetail_Table
    {
        public int Student_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public int Student_Age { get; set; }
        public string Gender_of_Student { get; set; }
        public string Pursuing_Department { get; set; }
        public string Student_Class { get; set; }
        public DateTime Year_Of_Joining { get; set; }
        public string Student_Location { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }
    }
}